name: learn-github-actions
run-name: ${{ github.actor }} is learning GitHub Actions
on: [push, workflow_dispatch]
jobs:
  build:
    runs-on: ubuntu-latest
    environment: prod
    steps:
      - name: Docker Login
        # You may pin to the exact commit or the version.
        # uses: docker/login-action@465a07811f14bebb1938fbed4728c6a1ff8901fc
        uses: docker/login-action@v2.2.0
        with:
          # Server address of Docker registry. If not set then will default to Docker Hub
          registry: registry.mumble.cloud
          # Username used to log against the Docker registry
          username: ${{ env.REGISTRY_USER }}
          # Password or personal access token used to log against the Docker registry
          password: ${{ env.REGISTRY_PASSWORD }}
          # Specifies whether the given registry is ECR (auto, true or false)
          #ecr: # optional, default is auto
          # Log out from the Docker registry at the end of a job
          #logout: # optional, default is true
      - name: Build and push Docker images
        # You may pin to the exact commit or the version.
        # uses: docker/build-push-action@44ea916f6c540f9302d50c2b1e5a8dc071f15cdf
        uses: docker/build-push-action@v4.1.0
        with:
          # Path to the Dockerfile
          file: ./Dockerfile
          # List of metadata for an image
          labels: ubu-test
          # Load is a shorthand for --output=type=docker
          # load: # optional, default is false
          # Set the networking mode for the RUN instructions during build
    # network: # optional
    # Do not use cache when building the image
    #no-cache: # optional, default is false
    # Do not cache specified stages
    #no-cache-filters: # optional
    # List of output destinations (format: type=local,dest=path)
    #outputs: # optional
    # List of target platforms for build
    # platforms: # optional
    # Generate provenance attestation for the build (shorthand for --attest=type=provenance)
    #provenance: # optional
    # Always attempt to pull all referenced images
    #pull: # optional, default is false
    # Push is a shorthand for --output=type=registry
    #push: true
    # Generate SBOM attestation for the build (shorthand for --attest=type=sbom)
    #sbom: # optional
    # List of secrets to expose to the build (e.g., key=string, GIT_AUTH_TOKEN=mytoken)
    #secrets: # optional
    # List of secret files to expose to the build (e.g., key=filename, MY_SECRET=./secret.txt)
    #secret-files: # optional
    # Size of /dev/shm (e.g., 2g)
    #shm-size: # optional
    # List of SSH agent socket or keys to expose to the build
    #ssh: # optional
    # List of tags
    #tags: # optional
    # Sets the target stage to build
    #target: # optional
    # Ulimit options (e.g., nofile=1024:1024)
    #ulimit: # optional
    # GitHub Token used to authenticate against a repository for Git context
    #github-token: # optional, default is ${{ github.token }}
  check-bats-version:
    if: false
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '14'
      - run: |
          env | sort   
      - run: npm install -g bats
      - run: bats -v
      - run: echo SD_VAR=${{ vars.SD_VAR }}
      - run: echo SDVAR=$vars.SD_VAR
